# Form implementation generated from reading ui file 'C:\Users\byzan\PycharmProjects\ui\trainidea1.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TrainingMenu(object):


    def retranslateUi(self, TrainingMenu):
        _translate = QtCore.QCoreApplication.translate
        TrainingMenu.setWindowTitle(_translate("TrainingMenu", " Training Menu"))
        self.training_label.setText(_translate("TrainingMenu", "Train Network"))
        self.epochs_label.setText(_translate("TrainingMenu", "Epochs"))
        self.verbiose_label.setText(_translate("TrainingMenu", "Verbiose Mode"))
        self.lrate_label.setText(_translate("TrainingMenu", "Initial Learning Rate       "))
        self.batch_size_label.setText(_translate("TrainingMenu", "Batch Size"))
        self.layers_tab.setTabText(self.layers_tab.indexOf(self.general_tab), _translate("TrainingMenu", "General"))
        self.enable_stop_label.setText(_translate("TrainingMenu", "Enable Stopping"))
        self.monitor_var_label.setText(_translate("TrainingMenu", "Monitored Variable        "))
        self.till_stop_label.setText(_translate("TrainingMenu", "Epochs Till Stop"))
        self.trigger_label.setText(_translate("TrainingMenu", "Stop Trigger"))
        self.restore_weight_label.setText(_translate("TrainingMenu", "Restore Weights"))
        self.layers_tab.setTabText(self.layers_tab.indexOf(self.early_stop_tab), _translate("TrainingMenu", "Stopping"))
        self.type_label.setText(_translate("TrainingMenu", "Decay Type                     "))
        self.rate_label.setText(_translate("TrainingMenu", "Decay Rate"))
        self.decay_start_label.setText(_translate("TrainingMenu", "Decay Start (Epochs)"))
        self.enable_scheduler_label.setText(_translate("TrainingMenu", "Enable Scheduler"))
        self.layers_tab.setTabText(self.layers_tab.indexOf(self.lrate_scheduler_tab), _translate("TrainingMenu", "Scheduler"))
        self.train_data_path_label.setText(_translate("TrainingMenu", "Training Data Path"))
        self.train_path_button.setText(_translate("TrainingMenu", "Select Folder"))
        self.valid_data_path_label.setText(_translate("TrainingMenu", "Validation Data Path"))
        self.valid_path_button.setText(_translate("TrainingMenu", "Select Folder"))
        self.valid_split_label.setText(_translate("TrainingMenu", "Validation Split"))
        self.valid_split_perc.setText(_translate("TrainingMenu", "0%"))
        self.folds_label.setText(_translate("TrainingMenu", "Number of Folds"))
        self.datasets_label.setText(_translate("TrainingMenu", "Max Samples"))
        self.subfolders_label.setText(_translate("TrainingMenu", "Include Subfolders"))
        self.valid_method_label.setText(_translate("TrainingMenu", "Validation Method"))
        self.data_source_label.setText(_translate("TrainingMenu", "Data Source"))
        self.train_button.setText(_translate("TrainingMenu", "Train"))
