# Form implementation generated from reading ui file 'train3.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TrainingMenu(object):
    def setupUi(self, TrainingMenu):
        TrainingMenu.setObjectName("TrainingMenu")
        TrainingMenu.resize(530, 941)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TrainingMenu.sizePolicy().hasHeightForWidth())
        TrainingMenu.setSizePolicy(sizePolicy)
        TrainingMenu.setMinimumSize(QtCore.QSize(509, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        TrainingMenu.setFont(font)
        TrainingMenu.setStyleSheet("/* General Styles */\n"
"QWidget {\n"
"    font:  \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    font-size: 10pt;\n"
"    color: rgb(99, 99, 99);\n"
"font-weight: bold;\n"
"}\n"
"\n"
"/* Combo Boxes */\n"
"QComboBox {\n"
"    font-size: 10pt;\n"
"    padding: 5px 10px; /* Increased padding */\n"
"    qproperty-alignment: \'AlignCenter\'; /* This may not work in some versions of Qt */\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    text-align: center;\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"}\n"
"\n"
"/* Push Buttons */\n"
"QPushButton {\n"
"    font-size: 10pt; /* Increased font size */\n"
"    padding: 4px 4px; /* Increased padding */\n"
"    background-color: #ffffff; /* White background */\n"
"    color: #333333; /* Dark gray text color */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"    border-radius: 4px;\n"
"    transition: background-color 0.3s, color 0.3s; /* Smooth transition for hover effects */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #dadbde; /* Light gray when pressed */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3daee9; /* Primary accent color */\n"
"    color: #ffffff; /* White text color when hovered */\n"
"    border: 1px solid #3daee9; /* Blue border when hovered */\n"
"}\n"
"\n"
"/* Text Browser */\n"
"QTextBrowser {\n"
"    font-size: 10pt;\n"
"    color: #333333; /* Dark gray text color */\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    font-size: 10pt;\n"
"    background-color: #f2f2f2; /* Light gray background for the tab content area */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"    border-radius: 4px;\n"
"    margin-top: 15px; /* Add margin between group boxes */\n"
"}\n"
"\n"
"/* Line Edits */\n"
"QLineEdit {\n"
"    font-size: 10pt;\n"
"    padding: 5px 10px; /* Increased padding */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"    border-radius: 4px;\n"
"    background-color: #ffffff; /* White background */\n"
"}\n"
"\n"
"/* Spin Boxes */\n"
"QSpinBox, QDoubleSpinBox {\n"
"    font-size: 10pt;\n"
"    padding: 5px 10px; /* Increased padding */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"    border-radius: 4px;\n"
"    background-color: #ffffff; /* White background */\n"
"}\n"
"\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button {\n"
"    width: 20px; /* Adjusted width */\n"
"    height: 14px; /* Adjusted height */\n"
"    padding: 0px; /* Removed padding */\n"
"    margin: 0px; /* Ensure no margins are applied */\n"
"    background-color: #dcdcdc; /* Slightly lighter gray background */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button {\n"
"    width: 20px; /* Adjusted width */\n"
"    height: 14px; /* Adjusted height */\n"
"    padding: 0px; /* Removed padding */\n"
"    margin: 0px; /* Ensure no margins are applied */\n"
"    background-color: #e0e0e0; /* Light gray background */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover, QDoubleSpinBox::up-button:hover,\n"
"QSpinBox::down-button:hover, QDoubleSpinBox::down-button:hover {\n"
"    background-color: #3daee9; /* Primary accent color */\n"
"    color: #ffffff; /* White text color when hovered */\n"
"    border: 1px solid #3daee9; /* Blue border when hovered */\n"
"}\n"
"\n"
"QSpinBox::up-arrow, QDoubleSpinBox::up-arrow {\n"
"    image: url(:/icons/up-arrow.png); /* Path to your custom up arrow icon */\n"
"    width: 8px; /* Adjusted width */\n"
"    height: 8px; /* Adjusted height */\n"
"    margin: auto;\n"
"}\n"
"\n"
"QSpinBox::down-arrow, QDoubleSpinBox::down-arrow {\n"
"    image: url(:/icons/down-arrow.png); /* Path to your custom down arrow icon */\n"
"    width: 8px; /* Adjusted width */\n"
"    height: 8px; /* Adjusted height */\n"
"    margin: auto;\n"
"}\n"
"\n"
"/* Check Boxes */\n"
"QCheckBox {\n"
"    font-size: 10pt;\n"
"    padding: 3px 8px; /* Adjusted padding to be more consistent */\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #3daee9; /* Primary accent color */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid #3daee9;\n"
"}\n"
"\n"
"/* Sliders */\n"
"QSlider {\n"
"    min-height: 20px;\n"
"    max-height: 20px;\n"
"    margin: 3px 0px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb; /* Light gray border */\n"
"    background-color: #f2f2f2; /* Light gray background */\n"
"    height: 6px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: #3daee9; /* Primary accent color */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    margin: -5px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: #5dc0ef; /* Lighter blue */\n"
"    border: 1px solid #3daee9;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: #3daee9; /* Primary accent color */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"    height: 6px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Specific Element Styles */\n"
"#training_label {\n"
"    font-size: 25pt;\n"
"    font-weight: bold;\n"
"    color: #333333; /* Dark gray text color */\n"
"    padding: 10px;\n"
"    background-color: #f2f2f2; /* Light gray background */\n"
"    border: 0px solid #c0c0c0; /* Light gray border */\n"
"    border-radius: 5px;\n"
"    text-align: center; /* Centered text */\n"
"}\n"
"\n"
"#layers_tab::pane {\n"
"    background-color: #f2f2f2; /* Light gray background for the tab content area */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"}\n"
"\n"
"#train_button {\n"
"    font-size: 12pt;\n"
"font-weight: bold;\n"
"    padding: 8px 16px; /* Increased padding */\n"
"    background-color: #ffffff; /* White background */\n"
"    color: #333333; /* Dark gray text color */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"    border-radius: 4px;\n"
"    transition: background-color 0.3s, color 0.3s; /* Smooth transition for hover effects */\n"
"}\n"
"\n"
"#train_button:pressed {\n"
"    background-color: #dadbde; /* Light gray when pressed */\n"
"}\n"
"\n"
"#train_button:hover {\n"
"    background-color: #3daee9; /* Primary accent color */\n"
"    color: #ffffff; /* White text color when hovered */\n"
"    border: 1px solid #3daee9; /* Blue border when hovered */\n"
"}\n"
"\n"
"/* Tab Bar Styles */\n"
"QTabBar::tab {\n"
"    background-color: white; /* Light blue background */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"    border-bottom-color: transparent; /* Makes the bottom border invisible */\n"
"    border-top-left-radius: 4px; /* Rounded corners on the top-left */\n"
"    border-top-right-radius: 4px; /* Rounded corners on the top-right */\n"
"    padding: 8px 15px; /* Increased padding to make tabs bigger */\n"
"    margin-right: 2px; /* Space between tabs */\n"
"    font-size: 10pt; /* Increased font size */\n"
"    min-width: 100px; /* Ensures the tab has a minimum width */\n"
"   min-height: 12px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #5dc0ef; /* Lighter blue */\n"
"    color: #ffffff; /* White text color for selected tab */\n"
"    border-color: #3daee9; /* Darker border color for the selected tab */\n"
"    border-bottom-color: #ffffff; /* Light gray background for the tab content area */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #3daee9; /* Primary accent color */\n"
"    color: #ffffff; /* White text color for hovered tab */\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    background-color: #ffffff; /* White background for the tab content area */\n"
"    border: 1px solid #c0c0c0; /* Light gray border */\n"
"    border-radius: 4px;\n"
"    padding: 10px; /* Padding inside the tab content area */\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=TrainingMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(509, 0))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 471, 911))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.training_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.training_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.training_layout.setContentsMargins(10, 10, 10, 0)
        self.training_layout.setObjectName("training_layout")
        self.training_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.training_label.sizePolicy().hasHeightForWidth())
        self.training_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        self.training_label.setFont(font)
        self.training_label.setLineWidth(0)
        self.training_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.training_label.setObjectName("training_label")
        self.training_layout.addWidget(self.training_label)
        self.training_frame = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.training_frame.sizePolicy().hasHeightForWidth())
        self.training_frame.setSizePolicy(sizePolicy)
        self.training_frame.setAutoFillBackground(True)
        self.training_frame.setStyleSheet("fields_frame:Qframe {\n"
"\n"
"background: rgb(249, 249, 249)\n"
"}")
        self.training_frame.setObjectName("training_frame")
        self.layers_tab = QtWidgets.QTabWidget(parent=self.training_frame)
        self.layers_tab.setGeometry(QtCore.QRect(0, 380, 451, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.layers_tab.sizePolicy().hasHeightForWidth())
        self.layers_tab.setSizePolicy(sizePolicy)
        self.layers_tab.setMinimumSize(QtCore.QSize(450, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setItalic(False)
        self.layers_tab.setFont(font)
        self.layers_tab.setStyleSheet("")
        self.layers_tab.setDocumentMode(False)
        self.layers_tab.setTabsClosable(False)
        self.layers_tab.setTabBarAutoHide(True)
        self.layers_tab.setObjectName("layers_tab")
        self.general_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.general_tab.sizePolicy().hasHeightForWidth())
        self.general_tab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(False)
        self.general_tab.setFont(font)
        self.general_tab.setObjectName("general_tab")
        self.formLayoutWidget_3 = QtWidgets.QWidget(parent=self.general_tab)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(40, 10, 691, 235))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.general_form = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.general_form.setContentsMargins(10, 10, 10, 10)
        self.general_form.setHorizontalSpacing(20)
        self.general_form.setVerticalSpacing(30)
        self.general_form.setObjectName("general_form")
        self.epochs_label = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.epochs_label.setFont(font)
        self.epochs_label.setObjectName("epochs_label")
        self.general_form.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.epochs_label)
        self.verbiose_label = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.verbiose_label.setFont(font)
        self.verbiose_label.setObjectName("verbiose_label")
        self.general_form.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.verbiose_label)
        self.batch_size_box = QtWidgets.QSpinBox(parent=self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batch_size_box.sizePolicy().hasHeightForWidth())
        self.batch_size_box.setSizePolicy(sizePolicy)
        self.batch_size_box.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.batch_size_box.setFont(font)
        self.batch_size_box.setObjectName("batch_size_box")
        self.general_form.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.batch_size_box)
        self.epochs_box = QtWidgets.QSpinBox(parent=self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epochs_box.sizePolicy().hasHeightForWidth())
        self.epochs_box.setSizePolicy(sizePolicy)
        self.epochs_box.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.epochs_box.setFont(font)
        self.epochs_box.setObjectName("epochs_box")
        self.general_form.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.epochs_box)
        self.lrate_box = QtWidgets.QDoubleSpinBox(parent=self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lrate_box.sizePolicy().hasHeightForWidth())
        self.lrate_box.setSizePolicy(sizePolicy)
        self.lrate_box.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.lrate_box.setFont(font)
        self.lrate_box.setObjectName("lrate_box")
        self.general_form.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lrate_box)
        self.lrate_label = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.lrate_label.setFont(font)
        self.lrate_label.setObjectName("lrate_label")
        self.general_form.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lrate_label)
        self.batch_size_label = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.batch_size_label.setFont(font)
        self.batch_size_label.setObjectName("batch_size_label")
        self.general_form.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.batch_size_label)
        self.verbiose_box = QtWidgets.QComboBox(parent=self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verbiose_box.sizePolicy().hasHeightForWidth())
        self.verbiose_box.setSizePolicy(sizePolicy)
        self.verbiose_box.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.verbiose_box.setFont(font)
        self.verbiose_box.setObjectName("verbiose_box")
        self.verbiose_box.addItem("")
        self.verbiose_box.addItem("")
        self.verbiose_box.addItem("")
        self.general_form.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.verbiose_box)
        self.layers_tab.addTab(self.general_tab, "")
        self.early_stop_tab = QtWidgets.QWidget()
        self.early_stop_tab.setObjectName("early_stop_tab")
        self.formLayoutWidget_4 = QtWidgets.QWidget(parent=self.early_stop_tab)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(40, 10, 471, 284))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.early_stop_form = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.early_stop_form.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.early_stop_form.setContentsMargins(10, 10, 10, 10)
        self.early_stop_form.setHorizontalSpacing(20)
        self.early_stop_form.setVerticalSpacing(30)
        self.early_stop_form.setObjectName("early_stop_form")
        self.enable_stop_label = QtWidgets.QLabel(parent=self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.enable_stop_label.setFont(font)
        self.enable_stop_label.setObjectName("enable_stop_label")
        self.early_stop_form.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.enable_stop_label)
        self.enable_stop_box = QtWidgets.QCheckBox(parent=self.formLayoutWidget_4)
        self.enable_stop_box.setText("")
        self.enable_stop_box.setObjectName("enable_stop_box")
        self.early_stop_form.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.enable_stop_box)
        self.monitor_var_label = QtWidgets.QLabel(parent=self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.monitor_var_label.setFont(font)
        self.monitor_var_label.setObjectName("monitor_var_label")
        self.early_stop_form.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.monitor_var_label)
        self.monitor_var_box = QtWidgets.QComboBox(parent=self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitor_var_box.sizePolicy().hasHeightForWidth())
        self.monitor_var_box.setSizePolicy(sizePolicy)
        self.monitor_var_box.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.monitor_var_box.setFont(font)
        self.monitor_var_box.setObjectName("monitor_var_box")
        self.monitor_var_box.addItem("")
        self.monitor_var_box.addItem("")
        self.monitor_var_box.addItem("")
        self.monitor_var_box.setItemText(2, "")
        self.early_stop_form.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.monitor_var_box)
        self.till_stop_label = QtWidgets.QLabel(parent=self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.till_stop_label.setFont(font)
        self.till_stop_label.setObjectName("till_stop_label")
        self.early_stop_form.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.till_stop_label)
        self.tilll_stop_box = QtWidgets.QSpinBox(parent=self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tilll_stop_box.sizePolicy().hasHeightForWidth())
        self.tilll_stop_box.setSizePolicy(sizePolicy)
        self.tilll_stop_box.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.tilll_stop_box.setFont(font)
        self.tilll_stop_box.setObjectName("tilll_stop_box")
        self.early_stop_form.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tilll_stop_box)
        self.trigger_label = QtWidgets.QLabel(parent=self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.trigger_label.setFont(font)
        self.trigger_label.setObjectName("trigger_label")
        self.early_stop_form.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.trigger_label)
        self.trigger_box = QtWidgets.QComboBox(parent=self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trigger_box.sizePolicy().hasHeightForWidth())
        self.trigger_box.setSizePolicy(sizePolicy)
        self.trigger_box.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.trigger_box.setFont(font)
        self.trigger_box.setObjectName("trigger_box")
        self.trigger_box.addItem("")
        self.trigger_box.addItem("")
        self.early_stop_form.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.trigger_box)
        self.restore_weights_box = QtWidgets.QCheckBox(parent=self.formLayoutWidget_4)
        self.restore_weights_box.setText("")
        self.restore_weights_box.setObjectName("restore_weights_box")
        self.early_stop_form.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.restore_weights_box)
        self.restore_weight_label = QtWidgets.QLabel(parent=self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.restore_weight_label.setFont(font)
        self.restore_weight_label.setObjectName("restore_weight_label")
        self.early_stop_form.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.restore_weight_label)
        self.layers_tab.addTab(self.early_stop_tab, "")
        self.lrate_scheduler_tab = QtWidgets.QWidget()
        self.lrate_scheduler_tab.setObjectName("lrate_scheduler_tab")
        self.formLayoutWidget_5 = QtWidgets.QWidget(parent=self.lrate_scheduler_tab)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(40, 10, 426, 311))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.lrate_scheduler_form = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.lrate_scheduler_form.setContentsMargins(10, 10, 10, 10)
        self.lrate_scheduler_form.setHorizontalSpacing(20)
        self.lrate_scheduler_form.setVerticalSpacing(30)
        self.lrate_scheduler_form.setObjectName("lrate_scheduler_form")
        self.type_label = QtWidgets.QLabel(parent=self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.type_label.setFont(font)
        self.type_label.setObjectName("type_label")
        self.lrate_scheduler_form.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.type_label)
        self.rate_label = QtWidgets.QLabel(parent=self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.rate_label.setFont(font)
        self.rate_label.setObjectName("rate_label")
        self.lrate_scheduler_form.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rate_label)
        self.rate_box = QtWidgets.QDoubleSpinBox(parent=self.formLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rate_box.sizePolicy().hasHeightForWidth())
        self.rate_box.setSizePolicy(sizePolicy)
        self.rate_box.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.rate_box.setFont(font)
        self.rate_box.setMaximum(1.0)
        self.rate_box.setSingleStep(0.1)
        self.rate_box.setProperty("value", 0.9)
        self.rate_box.setObjectName("rate_box")
        self.lrate_scheduler_form.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rate_box)
        self.decay_start_label = QtWidgets.QLabel(parent=self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.decay_start_label.setFont(font)
        self.decay_start_label.setObjectName("decay_start_label")
        self.lrate_scheduler_form.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.decay_start_label)
        self.decay_type_box = QtWidgets.QComboBox(parent=self.formLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decay_type_box.sizePolicy().hasHeightForWidth())
        self.decay_type_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.decay_type_box.setFont(font)
        self.decay_type_box.setObjectName("decay_type_box")
        self.decay_type_box.addItem("")
        self.decay_type_box.addItem("")
        self.lrate_scheduler_form.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.decay_type_box)
        self.decay_start_box = QtWidgets.QSpinBox(parent=self.formLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decay_start_box.sizePolicy().hasHeightForWidth())
        self.decay_start_box.setSizePolicy(sizePolicy)
        self.decay_start_box.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.decay_start_box.setFont(font)
        self.decay_start_box.setMinimum(0)
        self.decay_start_box.setMaximum(1000)
        self.decay_start_box.setProperty("value", 5)
        self.decay_start_box.setObjectName("decay_start_box")
        self.lrate_scheduler_form.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.decay_start_box)
        self.enable_scheduler_label = QtWidgets.QLabel(parent=self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.enable_scheduler_label.setFont(font)
        self.enable_scheduler_label.setObjectName("enable_scheduler_label")
        self.lrate_scheduler_form.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.enable_scheduler_label)
        self.enable_scheduler_box = QtWidgets.QCheckBox(parent=self.formLayoutWidget_5)
        self.enable_scheduler_box.setText("")
        self.enable_scheduler_box.setObjectName("enable_scheduler_box")
        self.lrate_scheduler_form.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.enable_scheduler_box)
        self.layers_tab.addTab(self.lrate_scheduler_tab, "")
        self.train_button = QtWidgets.QPushButton(parent=self.training_frame)
        self.train_button.setEnabled(True)
        self.train_button.setGeometry(QtCore.QRect(50, 760, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.train_button.setFont(font)
        self.train_button.setStyleSheet("")
        self.train_button.setObjectName("train_button")
        self.groupBox = QtWidgets.QGroupBox(parent=self.training_frame)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 451, 351))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_12 = QtWidgets.QWidget(parent=self.groupBox)
        self.formLayoutWidget_12.setGeometry(QtCore.QRect(20, 50, 411, 341))
        self.formLayoutWidget_12.setObjectName("formLayoutWidget_12")
        self.data_settings_form = QtWidgets.QFormLayout(self.formLayoutWidget_12)
        self.data_settings_form.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.data_settings_form.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.data_settings_form.setContentsMargins(5, 0, 5, 0)
        self.data_settings_form.setHorizontalSpacing(10)
        self.data_settings_form.setVerticalSpacing(30)
        self.data_settings_form.setObjectName("data_settings_form")
        self.train_data_path_label = QtWidgets.QLabel(parent=self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.train_data_path_label.setFont(font)
        self.train_data_path_label.setObjectName("train_data_path_label")
        self.data_settings_form.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.train_data_path_label)
        self.train_path_hbox = QtWidgets.QHBoxLayout()
        self.train_path_hbox.setSpacing(15)
        self.train_path_hbox.setObjectName("train_path_hbox")
        self.train_path_entry = QtWidgets.QLineEdit(parent=self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.train_path_entry.setFont(font)
        self.train_path_entry.setObjectName("train_path_entry")
        self.train_path_hbox.addWidget(self.train_path_entry)
        self.train_path_button = QtWidgets.QPushButton(parent=self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.train_path_button.setFont(font)
        self.train_path_button.setObjectName("train_path_button")
        self.train_path_hbox.addWidget(self.train_path_button)
        self.data_settings_form.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.train_path_hbox)
        self.valid_data_path_label = QtWidgets.QLabel(parent=self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.valid_data_path_label.setFont(font)
        self.valid_data_path_label.setObjectName("valid_data_path_label")
        self.data_settings_form.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.valid_data_path_label)
        self.valid_path_hbox = QtWidgets.QHBoxLayout()
        self.valid_path_hbox.setSpacing(15)
        self.valid_path_hbox.setObjectName("valid_path_hbox")
        self.valid_path_entry = QtWidgets.QLineEdit(parent=self.formLayoutWidget_12)
        self.valid_path_entry.setObjectName("valid_path_entry")
        self.valid_path_hbox.addWidget(self.valid_path_entry)
        self.valid_path_button = QtWidgets.QPushButton(parent=self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.valid_path_button.setFont(font)
        self.valid_path_button.setObjectName("valid_path_button")
        self.valid_path_hbox.addWidget(self.valid_path_button)
        self.data_settings_form.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.valid_path_hbox)
        self.datasets_label = QtWidgets.QLabel(parent=self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.datasets_label.setFont(font)
        self.datasets_label.setObjectName("datasets_label")
        self.data_settings_form.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.datasets_label)
        self.datasets_box = QtWidgets.QSpinBox(parent=self.formLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasets_box.sizePolicy().hasHeightForWidth())
        self.datasets_box.setSizePolicy(sizePolicy)
        self.datasets_box.setMinimumSize(QtCore.QSize(70, 20))
        self.datasets_box.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.datasets_box.setFont(font)
        self.datasets_box.setStyleSheet("")
        self.datasets_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.datasets_box.setAccelerated(False)
        self.datasets_box.setProperty("showGroupSeparator", False)
        self.datasets_box.setObjectName("datasets_box")
        self.data_settings_form.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.datasets_box)
        self.data_source_label = QtWidgets.QLabel(parent=self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.data_source_label.setFont(font)
        self.data_source_label.setObjectName("data_source_label")
        self.data_settings_form.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.data_source_label)
        self.valid_split_label = QtWidgets.QLabel(parent=self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.valid_split_label.setFont(font)
        self.valid_split_label.setObjectName("valid_split_label")
        self.data_settings_form.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.valid_split_label)
        self.valid_split_box = QtWidgets.QHBoxLayout()
        self.valid_split_box.setSpacing(30)
        self.valid_split_box.setObjectName("valid_split_box")
        self.valid_split_slider = QtWidgets.QSlider(parent=self.formLayoutWidget_12)
        self.valid_split_slider.setMaximumSize(QtCore.QSize(400, 26))
        self.valid_split_slider.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setItalic(False)
        self.valid_split_slider.setFont(font)
        self.valid_split_slider.setMaximum(100)
        self.valid_split_slider.setSingleStep(5)
        self.valid_split_slider.setPageStep(5)
        self.valid_split_slider.setSliderPosition(10)
        self.valid_split_slider.setTracking(True)
        self.valid_split_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.valid_split_slider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBothSides)
        self.valid_split_slider.setTickInterval(5)
        self.valid_split_slider.setObjectName("valid_split_slider")
        self.valid_split_box.addWidget(self.valid_split_slider)
        self.valid_split_perc = QtWidgets.QLabel(parent=self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.valid_split_perc.setFont(font)
        self.valid_split_perc.setObjectName("valid_split_perc")
        self.valid_split_box.addWidget(self.valid_split_perc)
        self.data_settings_form.setLayout(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.valid_split_box)
        self.spacer = QtWidgets.QLabel(parent=self.formLayoutWidget_12)
        self.spacer.setText("")
        self.spacer.setObjectName("spacer")
        self.data_settings_form.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.spacer)
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget_12)
        self.label.setText("")
        self.label.setObjectName("label")
        self.data_settings_form.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label)
        self.data_source_box = QtWidgets.QComboBox(parent=self.formLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_source_box.sizePolicy().hasHeightForWidth())
        self.data_source_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.data_source_box.setFont(font)
        self.data_source_box.setObjectName("data_source_box")
        self.data_source_box.addItem("")
        self.data_source_box.addItem("")
        self.data_settings_form.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.data_source_box)
        self.groupBox.raise_()
        self.layers_tab.raise_()
        self.train_button.raise_()
        self.training_layout.addWidget(self.training_frame)
        TrainingMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=TrainingMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 22))
        self.menubar.setObjectName("menubar")
        TrainingMenu.setMenuBar(self.menubar)
        self.training_status = QtWidgets.QStatusBar(parent=TrainingMenu)
        self.training_status.setObjectName("training_status")
        TrainingMenu.setStatusBar(self.training_status)

        self.retranslateUi(TrainingMenu)
        self.layers_tab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(TrainingMenu)

    def retranslateUi(self, TrainingMenu):
        _translate = QtCore.QCoreApplication.translate
        TrainingMenu.setWindowTitle(_translate("TrainingMenu", " Training Menu"))
        self.training_label.setText(_translate("TrainingMenu", "Train Network"))
        self.epochs_label.setText(_translate("TrainingMenu", "Epochs"))
        self.verbiose_label.setText(_translate("TrainingMenu", "Verbiose Mode"))
        self.lrate_label.setText(_translate("TrainingMenu", "Initial Learning Rate       "))
        self.batch_size_label.setText(_translate("TrainingMenu", "Batch Size"))
        self.verbiose_box.setItemText(0, _translate("TrainingMenu", "Silent "))
        self.verbiose_box.setItemText(1, _translate("TrainingMenu", "Progress Bar "))
        self.verbiose_box.setItemText(2, _translate("TrainingMenu", "One Line Per Epoch"))
        self.layers_tab.setTabText(self.layers_tab.indexOf(self.general_tab), _translate("TrainingMenu", "General"))
        self.enable_stop_label.setText(_translate("TrainingMenu", "Enable Stopping"))
        self.monitor_var_label.setText(_translate("TrainingMenu", "Monitored Variable        "))
        self.monitor_var_box.setItemText(0, _translate("TrainingMenu", "Validation Loss"))
        self.monitor_var_box.setItemText(1, _translate("TrainingMenu", "Validation Accuracy"))
        self.till_stop_label.setText(_translate("TrainingMenu", "Epochs Till Stop"))
        self.trigger_label.setText(_translate("TrainingMenu", "Stop Trigger"))
        self.trigger_box.setItemText(0, _translate("TrainingMenu", "Increase (Does not Decrease)"))
        self.trigger_box.setItemText(1, _translate("TrainingMenu", "Plateau (Does not Increase)"))
        self.restore_weight_label.setText(_translate("TrainingMenu", "Restore Weights"))
        self.layers_tab.setTabText(self.layers_tab.indexOf(self.early_stop_tab), _translate("TrainingMenu", "Stopping"))
        self.type_label.setText(_translate("TrainingMenu", "Decay Type                     "))
        self.rate_label.setText(_translate("TrainingMenu", "Decay Rate"))
        self.decay_start_label.setText(_translate("TrainingMenu", "Decay Start (Epochs)"))
        self.decay_type_box.setItemText(0, _translate("TrainingMenu", "Linear Decay"))
        self.decay_type_box.setItemText(1, _translate("TrainingMenu", "Exponential Decay"))
        self.enable_scheduler_label.setText(_translate("TrainingMenu", "Enable Scheduler"))
        self.layers_tab.setTabText(self.layers_tab.indexOf(self.lrate_scheduler_tab), _translate("TrainingMenu", "Scheduler"))
        self.train_button.setText(_translate("TrainingMenu", "Train"))
        self.train_data_path_label.setText(_translate("TrainingMenu", "Training Data Path"))
        self.train_path_button.setText(_translate("TrainingMenu", "Select Folder"))
        self.valid_data_path_label.setText(_translate("TrainingMenu", "Validation Data Path"))
        self.valid_path_button.setText(_translate("TrainingMenu", "Select Folder"))
        self.datasets_label.setText(_translate("TrainingMenu", "Total Datasets"))
        self.data_source_label.setText(_translate("TrainingMenu", "Validation Data Source    "))
        self.valid_split_label.setText(_translate("TrainingMenu", "Validation Split"))
        self.valid_split_perc.setText(_translate("TrainingMenu", "10%"))
        self.data_source_box.setItemText(0, _translate("TrainingMenu", "Split Training Data"))
        self.data_source_box.setItemText(1, _translate("TrainingMenu", "Data From Seperate Path"))
