# Form implementation generated from reading ui file 'train3.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TrainingMenu(object):
    def setupUi(self, TrainingMenu):


    def retranslateUi(self, TrainingMenu):
        _translate = QtCore.QCoreApplication.translate
        TrainingMenu.setWindowTitle(_translate("TrainingMenu", " Training Menu"))
        self.training_label.setText(_translate("TrainingMenu", "Train Network"))
        self.epochs_label.setText(_translate("TrainingMenu", "Epochs"))
        self.verbiose_label.setText(_translate("TrainingMenu", "Verbiose Mode"))
        self.lrate_label.setText(_translate("TrainingMenu", "Initial Learning Rate       "))
        self.batch_size_label.setText(_translate("TrainingMenu", "Batch Size"))
        self.verbiose_box.setItemText(0, _translate("TrainingMenu", "Silent "))
        self.verbiose_box.setItemText(1, _translate("TrainingMenu", "Progress Bar "))
        self.verbiose_box.setItemText(2, _translate("TrainingMenu", "One Line Per Epoch"))
        self.layers_tab.setTabText(self.layers_tab.indexOf(self.general_tab), _translate("TrainingMenu", "General"))
        self.enable_stop_label.setText(_translate("TrainingMenu", "Enable Stopping"))
        self.monitor_var_label.setText(_translate("TrainingMenu", "Monitored Variable        "))
        self.monitor_var_box.setItemText(0, _translate("TrainingMenu", "Validation Loss"))
        self.monitor_var_box.setItemText(1, _translate("TrainingMenu", "Validation Accuracy"))
        self.till_stop_label.setText(_translate("TrainingMenu", "Epochs Till Stop"))
        self.trigger_label.setText(_translate("TrainingMenu", "Stop Trigger"))
        self.trigger_box.setItemText(0, _translate("TrainingMenu", "Increase (Does not Decrease)"))
        self.trigger_box.setItemText(1, _translate("TrainingMenu", "Plateau (Does not Increase)"))
        self.restore_weight_label.setText(_translate("TrainingMenu", "Restore Weights"))
        self.layers_tab.setTabText(self.layers_tab.indexOf(self.early_stop_tab), _translate("TrainingMenu", "Stopping"))
        self.type_label.setText(_translate("TrainingMenu", "Decay Type                     "))
        self.rate_label.setText(_translate("TrainingMenu", "Decay Rate"))
        self.decay_start_label.setText(_translate("TrainingMenu", "Decay Start (Epochs)"))
        self.decay_type_box.setItemText(0, _translate("TrainingMenu", "Linear Decay"))
        self.decay_type_box.setItemText(1, _translate("TrainingMenu", "Exponential Decay"))
        self.enable_scheduler_label.setText(_translate("TrainingMenu", "Enable Scheduler"))
        self.layers_tab.setTabText(self.layers_tab.indexOf(self.lrate_scheduler_tab), _translate("TrainingMenu", "Scheduler"))
        self.train_button.setText(_translate("TrainingMenu", "Train"))
        self.train_data_path_label.setText(_translate("TrainingMenu", "Training Data Path"))
        self.train_path_button.setText(_translate("TrainingMenu", "Select Folder"))
        self.valid_data_path_label.setText(_translate("TrainingMenu", "Validation Data Path"))
        self.valid_path_button.setText(_translate("TrainingMenu", "Select Folder"))
        self.datasets_label.setText(_translate("TrainingMenu", "Total Datasets"))
        self.data_source_label.setText(_translate("TrainingMenu", "Validation Data Source    "))
        self.valid_split_label.setText(_translate("TrainingMenu", "Validation Split"))
        self.valid_split_perc.setText(_translate("TrainingMenu", "10%"))
        self.data_source_box.setItemText(0, _translate("TrainingMenu", "Split Training Data"))
        self.data_source_box.setItemText(1, _translate("TrainingMenu", "Data From Seperate Path"))
